---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.20-5.1"
  amd64: "ghcr.io/home-assistant/amd64-base:3.20-5.1"
  armhf: "ghcr.io/home-assistant/armhf-base:3.20-5.1"
  armv7: "ghcr.io/home-assistant/armv7-base:3.20-5.1"
  i386: "ghcr.io/home-assistant/i386-base:3.20-5.1"
args:
  TEMPIO_VERSION: "2021.09.0"
labels:
  io.hass.version: "1.0.48"
  io.hass.type: "addon"
  io.hass.arch: "aarch64|amd64|armhf|armv7|i386" 