---
name: "BLE Scanner"
description: "MQTT-based BLE scanner compatible with smartbed-mqtt patterns for discovering and managing BLE devices via ESP32 proxies"
version: "1.0.62"
slug: "ble_scanner"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
hassio_api: true
homeassistant_api: true
ingress: true
ingress_port: 8099
panel_icon: mdi:bluetooth
boot: auto
# Security restrictions for high rating (using proper HA schema)
host_network: false
privileged: []  # Empty list = no privileged access (was boolean, now correct list)
full_access: false
devices: []
ports: {}
options:
  bleProxies:
    - host: "192.168.1.109"
      port: 6053
      password: ""
  mqtt:
    host: "<auto_detect>"
    port: 1883
    username: "<auto_detect>"
    password: "<auto_detect>"
    discovery: true
schema:
  bleProxies:
    - host: str
      port: "int(1,65535)?"
      password: "str?"
  mqtt:
    host: "str?"
    port: "int(1,65535)?"
    username: "str?"
    password: "str?"
    discovery: "bool?" 