---
name: "BLE Scanner"
version: "1.0.46"
slug: "ble_scanner"
description: "Standalone BLE scanner with web UI for discovering and managing BLE devices"
url: "https://github.com/bramboe/octo-mqtt-new"
maintainer: "Bram Boersma"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
init: false
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: "Web UI"
ingress: true
ingress_port: 8099
ingress_entry: /
panel_icon: mdi:bluetooth
homeassistant_api: false
map:
  - config:rw
  - ssl:ro
options:
  bleProxies:
    - host: "192.168.1.100"
      port: 6053
      password: ""
  mqtt_host: "<auto_detect>"
  mqtt_port: 1883
  mqtt_username: "<auto_detect>"
  mqtt_password: "<auto_detect>"
  mqtt_discovery: false
schema:
  bleProxies:
    - host: str
      port: int
      password: str
  mqtt_host: str
  mqtt_port: int
  mqtt_username: str
  mqtt_password: str
  mqtt_discovery: bool 