---
name: "BLE Scanner"
description: "MQTT-based BLE scanner compatible with smartbed-mqtt for discovering and managing BLE devices via ESP32 proxies"
version: "1.0.48"
slug: "ble_scanner"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: application
hassio_api: true
homeassistant_api: true
host_network: true
privileged:
  - NET_ADMIN
  - SYS_ADMIN
boot: auto
options:
  bleProxies:
    - host: "192.168.1.109"
      port: 6053
      password: ""
  mqtt:
    host: ""
    port: 1883
    username: ""
    password: ""
    discovery: true
schema:
  bleProxies:
    - host: str
      port: int(1,65535)?
      password: str?
  mqtt:
    host: str?
    port: int(1,65535)?
    username: str?
    password: str?
    discovery: bool?
ports:
  8099/tcp: 8099
webui: "http://[HOST]:[PORT:8099]" 